### ISSUE TITLE
nonexistent commit id error for buildrump.sh submodule

### ISSUE THREAD

**Issue by justinc1** [libos-nuse/rumprun#1]
After fresh git clone, I got non-existent commit id.

```
justin_cinkelj@jcpc:~/devel/oor/libos-nuse/rumprun$ git submodule init
Submodule 'buildrump.sh' (https://github.com/libos-nuse/buildrump.sh) registered for path 'buildrump.sh'
Submodule 'linux' (git://github.com/libos-nuse/lkl-linux) registered for path 'linux'
Submodule 'musl' (git://github.com/libos-nuse/musl.git) registered for path 'musl'
Submodule 'src-netbsd' (https://github.com/rumpkernel/src-netbsd) registered for path 'src-netbsd'

justin_cinkelj@jcpc:~/devel/oor/libos-nuse/rumprun$ git submodule update
Cloning into '/home/justin_cinkelj/devel/oor/libos-nuse/rumprun/buildrump.sh'...
Cloning into '/home/justin_cinkelj/devel/oor/libos-nuse/rumprun/linux'...
Cloning into '/home/justin_cinkelj/devel/oor/libos-nuse/rumprun/musl'...
Cloning into '/home/justin_cinkelj/devel/oor/libos-nuse/rumprun/src-netbsd'...
error: Server does not allow request for unadvertised object 5a1633f574bc416531f0fa4280709b29416d874f
Fetched in submodule path 'buildrump.sh', but it did not contain 5a1633f574bc416531f0fa4280709b29416d874f. Direct fetching of that commit failed.

justin_cinkelj@jcpc:~/devel/oor/libos-nuse/rumprun$ git status
On branch lkl-musl
Your branch is up-to-date with 'origin/lkl-musl'.
```

**Comment by justinc1** [comment]
Commit in https://github.com/libos-nuse/buildrump.sh/tree/linux-libos 9c9b022cb2115734935e50600c867a3bc230b32c is parent of 5a1633f574bc416531f0fa4280709b29416d874f. So only one push was not done?

**Comment by thehajime** [comment]
sorry for the trouble.
I think I did `git push -f` with those submodules for the use of different repository (https://github.com/libos-nuse/frankenlibc). 

for the moment you can work around by manually checkouting `linux-libos` branch.

**Comment by justinc1** [comment]
I think that was the intention.
https://github.com/libos-nuse/buildrump.sh/commit/238ed1fe120b1a71898a9d412f67376c9f01cb30 and https://github.com/libos-nuse/buildrump.sh/commit/5a1633f574bc416531f0fa4280709b29416d874f are almost identical.

And thank you for making lkl based unikernel. "sorry for the trouble" - far far outweighted by all your work.

**Comment by justinc1** [comment]
While above patch (which is same as using linux-libos branch of https://github.com/libos-nuse/buildrump.sh anyway) helps to build, I get x86_64-rumprun-netbsd-gcc. But is should be x86_64-rumprun-linux-gcc, right? And after rumprun-bake, output image has for example symbol (nm test.bin) ffs_copyonwrite - which seems to be BSD-ish. I guess I should pass some extra flag while following tutorial at https://github.com/rumpkernel/wiki/wiki/Repo:-rumprun .

Or, maybe I should follow entirely different tutorial in first place?

**Comment by justinc1** [comment]
Maybe?
```
xlab@or-libos:/home/justin_cinkelj/devel/oor/libos-nuse/rumprun$ ./build-rr.sh -r linux hw 
```
(instead of only ```./build-rr.sh hw ```)

**Comment by thehajime** [comment]
this repository/branch are work in progress behind pull request, though there are no news recently.  Thus I have frequently did (and will do) force push so it might cause some inconsistency.

For wiki I planned to update once the PR is merged but not yet.  So far there is no document on this.

> Maybe?
> 
> xlab@or-libos:/home/justin_cinkelj/devel/oor/libos-nuse/rumprun$ ./build-rr.sh -r linux hw

yes.

**Comment by thehajime** [comment]
I will try to update libos-nuse/rumprun to avoid missing links in my spare time.
